baseurl = "http://eli5.it/"
languageCode = "en-US"
title = "Explain IT Like I'm 5"
theme = "code-editor"

author = "Fabio Bier"
copyright = "Creative Commons Attribution 4.0 International"

[params]
  author = "Fabio Bier"
  locale = "en-US"
  disqusShortname = "xblackbytesx"

[[menu.main]]
  name   = "Linux"
  url    = "/categories/linux"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Install Guides"
  url    = "/series/install guides"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Tooling"
  url    = "/categories/tooling"
  weight = 0
  pre    = ""

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[social]
  twitter = "xblackbytesx"
  github  = "xblackbytesx"
