baseurl = "http://eli5.it/"
languageCode = "en-US"
title = "Explain IT Like I'm 5"
theme = "darkdoc"

author = "Fabio Bier"
copyright = "Creative Commons Attribution 4.0 International"

[Params]
  Author = "Fabio Bier"
  disqusShortname = "xblackbytesx"

[[menu.main]]
  name   = "Linux"
  url    = "/categories/linux"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Devops"
  url    = "/categories/devops"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Install Guides"
  url    = "/series/install guides"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Tooling"
  url    = "/categories/tooling"
  weight = 0
  pre    = ""

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[social]
  twitter = "xblackbytesx"
  github  = "xblackbytesx"
