theme = "darkdoc"
languageCode = "en-us"
title = "Explain IT Like I'm 5"
baseurl = "http://eli5.it/"
author = "Fabio Bier"
copyright = "Creative Commons Attribution 4.0 International"

[[menu.main]]
  name   = "Linux"
  url    = "/categories/linux"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Install Guides"
  url    = "/series/install guides"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Tooling"
  url    = "/categories/tooling"
  weight = 0
  pre    = ""

[Params]
  Author = "Fabio Bier"
  disqusShortname = "xblackbytesx"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[social]
  twitter = "xblackbytesx"
  github  = "xblackbytesx"
