baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "xblackbytesx"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title = "Explain IT Like I'm 5"
  subtitle = "Port of Casper 2.x for Hugo"

  cover = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "xblackbytesx"
  githubName = "xblackbytesx"

  logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name   = "Linux"
  url    = "/categories/linux"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Install Guides"
  url    = "/series/install guides"
  weight = 0
  pre    = ""
[[menu.main]]
  name   = "Tooling"
  url    = "/categories/tooling"
  weight = 0
  pre    = ""

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
